AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'
  CloudFormationBucket:
    Type: String
    Description: 'The S3 bucket for CloudFormation templates.'

Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateCodePipelineBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CodePipelineBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CloudFormationS3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateCloudFormationBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CloudFormationBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Conditions:
  CreateCodePipelineBucket: !Equals [ !Ref CodePipelineBucket, "" ]
  CreateCloudFormationBucket: !Equals [ !Ref CloudFormationBucket, "" ]