AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'

  CloudFormationBucket:
    Type: String
    Description: 'The S3 bucket for CloudFormation templates.'

Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
     BucketName: !Join 
       - '-'
       - - !Ref CodePipelineBucket
         - !Ref AWS::AccountId
     PublicAccessBlockConfiguration:
       BlockPublicAcls: true
       BlockPublicPolicy: true
       IgnorePublicAcls: true
       RestrictPublicBuckets: true
     BucketEncryption:
       ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
  CloudFormationS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - '-'
        - - !Ref CloudFormationBucket
          - !Ref AWS::AccountId
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
  
Outputs:
  CodePipelineBucketName:
    Description: "Name of the S3 bucket used to store CodePipeline artifacts"
    Value: 
      Ref: CodePipelineS3Bucket
    Export:
      Name: CodePipelineBucketName

  CloudFormationBucketName:
    Description: "Name of the S3 bucket used to store CloudFormation templates"
    Value: 
      Ref: CloudFormationS3Bucket
    Export:
      Name: CloudFormationBucketName
