AWSTemplateFormatVersion: 2010-09-09

Parameters:
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'

  CloudFormationBucket:
    Type: String
    Description: 'The S3 bucket for CloudFormation templates.'

Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
     BucketName: 
       Fn::Join: 
       - '-'
       - - Fn::Ref: CodePipelineBucket
         - Fn::Ref: AWS::AccountId
     PublicAccessBlockConfiguration:
       BlockPublicAcls: true
       BlockPublicPolicy: true
       IgnorePublicAcls: true
       RestrictPublicBuckets: true
     BucketEncryption:
       ServerSideEncryptionConfiguration:
         - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
 
  CloudFormationS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 
        Fn::Join:
        - '-'
        - - Fn::Ref: CloudFormationBucket
          - Fn::Ref: AWS::AccountId
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
Outputs:
  CodePipelineBucketOutput:
    Value: 
      Fn::Ref: CodePipelineS3Bucket
    Export:
      Name: CodePipelineBucketName

  CloudFormationBucketOutput:
    Value: 
      Fn::Ref: CloudFormationS3Bucket
    Export:
      Name: CloudFormationBucketName
